# Site settings
name: Benjamin Joyce's blog
title: Benjamin Joyce's blog
description: Posts about the web, business, and other stuff I do in my free time.
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://benjaminjoyce.com" # the base hostname & protocol for your site
twitter_username: BenJoyceCT
github_username:  BenJoyceCT

# Build settings
markdown: redcarpet
# pygments: true

exclude: [node_modules]
